version: '3'

services:
    db:
        build:
            context: api
            dockerfile: Dockerfile.postgres
        ports:
            - "5432:5432"
        volumes:
            - ./api/db/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        restart: always

    front:
        build:
            context: front
            dockerfile: Dockerfile.front
        ports: 
            - "3000:3000"
        depends_on:
            - db
        restart: always