/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiClient } from './client';
export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AddToQueueRequest } from './models/AddToQueueRequest';
export type { AddToQueueResponse } from './models/AddToQueueResponse';
export type { Album } from './models/Album';
export type { AlbumStats } from './models/AlbumStats';
export type { Artist } from './models/Artist';
export type { ArtistStats } from './models/ArtistStats';
export type { ClearQueueResponse } from './models/ClearQueueResponse';
export type { Device } from './models/Device';
export type { Error } from './models/Error';
export type { GetAllDevicesResponse } from './models/GetAllDevicesResponse';
export type { getArtistAlbumsResponse } from './models/getArtistAlbumsResponse';
export type { getArtistPlaylistsResponse } from './models/getArtistPlaylistsResponse';
export type { getArtistsResponse } from './models/getArtistsResponse';
export type { getArtistTopTracksResponse } from './models/getArtistTopTracksResponse';
export type { GetCurrentDeviceResponse } from './models/GetCurrentDeviceResponse';
export type { GetQueueResponse } from './models/GetQueueResponse';
export type { getSingleArtist } from './models/getSingleArtist';
export type { getTrackAlbumResponse } from './models/getTrackAlbumResponse';
export type { getTrackArtistResponse } from './models/getTrackArtistResponse';
export type { getTrackResponse } from './models/getTrackResponse';
export type { loginRequest } from './models/loginRequest';
export type { loginResponse } from './models/loginResponse';
export type { MoveInQueueRequest } from './models/MoveInQueueRequest';
export type { MoveInQueueResponse } from './models/MoveInQueueResponse';
export type { PauseResponse } from './models/PauseResponse';
export type { PlaybackStateResponse } from './models/PlaybackStateResponse';
export type { PlaybackStatus } from './models/PlaybackStatus';
export type { Playlist } from './models/Playlist';
export type { playlistCreateRequest } from './models/playlistCreateRequest';
export type { PlaylistResponse } from './models/PlaylistResponse';
export type { playlistSingleResponse } from './models/playlistSingleResponse';
export type { playlistsResponse } from './models/playlistsResponse';
export type { playlistTracksResponse } from './models/playlistTracksResponse';
export type { playlistUpdateRequest } from './models/playlistUpdateRequest';
export type { PlayTrackRequest } from './models/PlayTrackRequest';
export type { PlayTrackResponse } from './models/PlayTrackResponse';
export type { PrevResponse } from './models/PrevResponse';
export type { RegisterDeviceRequest } from './models/RegisterDeviceRequest';
export type { RegisterDeviceResponse } from './models/RegisterDeviceResponse';
export type { RemoveFromQueueRequest } from './models/RemoveFromQueueRequest';
export type { RemoveFromQueueResponse } from './models/RemoveFromQueueResponse';
export type { ResumeResponse } from './models/ResumeResponse';
export type { searchQueryResponse } from './models/searchQueryResponse';
export type { SearchResult } from './models/SearchResult';
export type { SeekResponse } from './models/SeekResponse';
export type { Service } from './models/Service';
export type { ServiceResponse } from './models/ServiceResponse';
export type { SetCurrentDeviceRequest } from './models/SetCurrentDeviceRequest';
export type { SetCurrentDeviceResponse } from './models/SetCurrentDeviceResponse';
export type { SetQualityResponse } from './models/SetQualityResponse';
export type { SetRepeatResponse } from './models/SetRepeatResponse';
export type { SetShuffleResponse } from './models/SetShuffleResponse';
export type { SetVolumeResponse } from './models/SetVolumeResponse';
export type { SkipResponse } from './models/SkipResponse';
export type { ssoUrl } from './models/ssoUrl';
export type { Tag } from './models/Tag';
export type { TagStats } from './models/TagStats';
export type { Track } from './models/Track';
export type { TrackStats } from './models/TrackStats';
export type { User } from './models/User';
export type { Widget } from './models/Widget';

export { ArtistService } from './services/ArtistService';
export { AuthenticationService } from './services/AuthenticationService';
export { DevicesService } from './services/DevicesService';
export { PlaybackService } from './services/PlaybackService';
export { PlaylistService } from './services/PlaylistService';
export { SearchService } from './services/SearchService';
export { ServicesService } from './services/ServicesService';
export { SsoService } from './services/SsoService';
export { StatsService } from './services/StatsService';
export { TrackService } from './services/TrackService';
export { WidgetService } from './services/WidgetService';
