name: Build Frontend
on: [workflow_call, workflow_dispatch]

jobs:
  build-front:
    name: Build Front
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ./apps/api/node_modules
            ./apps/app/node_modules
            ./apps/front/node_modules
            ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - run: npm run build
        working-directory: ./apps/front
        name: Build front
      - name: Upload Artifcat
        id: upload
        uses: actions/upload-artifact@v2
        with:
          name: front
          path: ./apps/front/dist
