name: Builder
on: [pull_request, workflow_dispatch]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ./apps/api/node_modules
            ./apps/app/node_modules
            ./apps/front/node_modules
            ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
      - run: npm i
        if: steps.cache.outputs.cache-hit != 'true'
        name: Install dependencies
  lint:
    strategy:
      matrix:
        directory: [ "app", "api", "front" ]
      fail-fast: false
    name: Lint
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ./apps/api/node_modules
            ./apps/app/node_modules
            ./apps/front/node_modules
            ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - run: npm run lint
        working-directory: ./apps/${{matrix.directory}}
        name: Lint
  prettier:
    strategy:
      matrix:
        directory: [ "app", "api", "front" ]
    name: Prettier
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ./apps/api/node_modules
            ./apps/app/node_modules
            ./apps/front/node_modules
            ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - run: npm run prettier
        working-directory: ./apps/${{matrix.directory}}
        name: Prettier
  openapi:
    needs: install-dependencies
    name: Validate OpenAPI Schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - run: npm run validate-swagger
        working-directory: ./apps/api
        name: Validate OpenAPI Schema
  build-app:
    name: Build App
    needs: [lint, prettier, openapi]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platforms: [ "ios", "android" ]
      fail-fast: false
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ./apps/api/node_modules
            ./apps/app/node_modules
            ./apps/front/node_modules
            ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Setup Expo
        uses: expo/expo-github-action@v5
        with:
            expo-version: 4.x
            expo-token: ${{ secrets.EXPO_TOKEN }}
            expo-cache: true
      - name: Build ${{matrix.platforms}} on EAS
        working-directory: ./apps/app
        run: npx eas-cli build --platform ${{matrix.platforms}} --non-interactive
      - name: Upload Artifcat
        id: upload
        uses: actions/upload-artifact@v2
        with:
          name: app-${{matrix.platforms}}
          path: ./apps/app/dist
  build-front:
    name: Build Front
    needs: [lint, prettier, openapi]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ./apps/api/node_modules
            ./apps/app/node_modules
            ./apps/front/node_modules
            ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - run: npm run build
        working-directory: ./apps/front
        name: Build front
      - name: Upload Artifcat
        id: upload
        uses: actions/upload-artifact@v2
        with:
          name: front
          path: ./apps/front/dist
  build-api:
    name: Build API
    needs: [lint, prettier, openapi]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ./apps/api/node_modules
            ./apps/app/node_modules
            ./apps/front/node_modules
            ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - run: npm run build
        working-directory: ./apps/api
        name: Build api
      - name: Upload Artifcat
        id: upload
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: ./apps/api/dist
