name: Install Dependencies
on: [ workflow_call, workflow_dispatch ]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ./apps/api/node_modules
            ./apps/app/node_modules
            ./apps/front/node_modules
            ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
      - run: npm i
        if: steps.cache.outputs.cache-hit != 'true'
        name: Install dependencies
