name: Lint Apps
on: [workflow_call, workflow_dispatch]

jobs:
  lint:
    strategy:
      matrix:
        directory: [ "app", "api", "front" ]
      fail-fast: false
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ./apps/api/node_modules
            ./apps/app/node_modules
            ./apps/front/node_modules
            ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - run: npm run lint
        working-directory: ./apps/${{matrix.directory}}
        name: Lint
